title: Alves Viana Junior, Arnaldo.
logo: /assets/img/arnaldojr.jpeg
description: <small>nov 29, 2020</small>
show_downloads: false
social_links:
  github: arnaldojr
  linkedin: arnaldo-alves-viana-junior-b3192334
  youtube: UCb6MEkxngDA5E1XBs_zULgQ/featured?view_as=subscriber

theme: jekyll-theme-minimal
